### ISSUE TITLE
bot comes only and reply for help 1time after no more help cmd works

### ISSUE THREAD

**Issue by Nangyalashraf** [protyodev/botmanager#1]
[WS => Shard 0] Heartbeat acknowledged, latency of 269ms.
[🚩 ANTI-CRASH] UNCAUGHT EXCEPTION MONITOR

[🚩 ANTI-CRASH] UNCAUGHT EXCEPTION
TypeError: Cannot read properties of undefined (reading 'rawPosition')
    at Client.<anonymous> (C:\Users\Barya\Desktop\BotManager-src\modules\commands.js:4423:108)
    at Client.emit (node:events:402:35)
    at MessageCreateAction.handle (C:\Users\Barya\Desktop\BotManager-src\node_modules\discord.js\src\client\actions\MessageCreate.js:26:14)
    at Object.module.exports [as MESSAGE_CREATE] (C:\Users\Barya\Desktop\BotManager-src\node_modules\discord.js\src\client\websocket\handlers\MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (C:\Users\Barya\Desktop\BotManager-src\node_modules\discord.js\src\client\websocket\WebSocketManager.js:351:31)
    at WebSocketShard.onPacket (C:\Users\Barya\Desktop\BotManager-src\node_modules\discord.js\src\client\websocket\WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (C:\Users\Barya\Desktop\BotManager-src\node_modules\discord.js\src\client\websocket\WebSocketShard.js:301:10)
    at WebSocket.onMessage (C:\Users\Barya\Desktop\BotManager-src\node_modules\ws\lib\event-target.js:199:18)
    at WebSocket.emit (node:events:390:28)
    at Receiver.receiverOnMessage (C:\Users\Barya\Desktop\BotManager-src\node_modules\ws\lib\websocket.js:1137:20)
=== UNCAUGHT EXCEPTION ===

 [Status Update] :: 0

**Comment by protyodev** [comment]
Change the IDs from commands.js
